import Head from "next/head";
import Image from "next/image";
export default function contact() {
    return(
        <>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pt-0"></section>

            <section>
                <div className="container w-[85%] mx-auto">
                    <div className="relative text-center w-[40%] mx-auto">
                      <Image src="/img/line-star.svg" className="rotate-180 w-[30%] left-[-6%] absolute top-[0%]" alt="Facebook" width="500" height="300"/>
                      <Image src="/img/line-star.svg" className="w-[30%] right-[-6%] absolute top-[0%]" alt="Facebook" width="500" height="300"/>
                      <h3 className="font-Avgardn tracking-[10px] uppercase leading-none text-[#bda37f] text-[30px] md:text-[40px] 3xl:text-[40px]">Contact Us</h3>
                    </div>
                    <div className="w-[80%] mx-auto flex items-center mt-14">
                        <Image src="/img/awards/matrix-logo.svg" className="w-fit max-h-[120px] mr-8" alt="Facebook" width="300" height="300"/>
                        <div>
                            <p class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px]">Head Office<br></br>Wisma Matrix, No.57, Jalan Tun Dr. Ismail,<br></br>70200 Seremban, Negeri Sembilan D.K. Malaysia</p>
                            <div className="flex items-center">
                                <a href="tel:067642688" class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px] mr-3">T +606 764 2688</a>
                                <a href="tel:0676426288" class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px]">F +606 764 6288</a>
                            </div>
                        </div>
                    </div>
                    <div className="w-[80%] mx-auto mt-14">
                        <div className="flex items-center justify-center">
                            <div className="flex items-center flex-1 border-solid border border-[#bda37f] border-b-0 border-t-0 border-l-0">
                                <Image src="/img/levia-logo.svg" className="w-fit max-h-[120px] mr-8" alt="Facebook" width="300" height="300"/>
                                <div>
                                    <p class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px]">Branch Office<br></br>A-1-5, Block A, Setiawalk, Persiaran Wawasan,<br></br>
                                    Pusat Bandar Puchong, 41760 Puchong,<br></br>Selangor Malaysia.</p>
                                    <div>
                                        <a href="tel:0327877922" class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px] mr-3">T +603 278 7792</a>
                                    </div>
                                </div>
                            </div>
                            <div className="flex items-center flex-1 justify-end">
                                <Image src="/img/levia-logo.svg" className="w-fit max-h-[120px] mr-8" alt="Facebook" width="300" height="300"/>
                                <div>
                                    <p class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px]">Branch Office<br></br>A-1-5, Block A, Setiawalk, Persiaran Wawasan,<br></br>
                                    Pusat Bandar Puchong, 41760 Puchong,<br></br>Selangor Malaysia.</p>
                                    <div>
                                        <a href="tel:0327877922" class="font-Avgardn text-[#bda37f] leading-7 tracking-[1px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px] mr-3">T +603 278 7792</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="pt-0">
                <div className="container w-[85%] mx-auto">
                    <div className="relative text-center w-[70%] mx-auto">
                      <Image src="/img/awards/award-title.svg" className="w-[60%] mx-auto" alt="Facebook" width="1000" height="300"/>
                    </div>
                    <div className="w-[80%] mx-auto flex items-center justify-center pt-8 mt-8">
                        <img src="/img/awards/award1.svg" className="max-h-[120px] w-full object-contain mr-5"></img>
                        <img src="/img/awards/award2.svg" className="max-h-[120px] w-full object-contain mr-5"></img>
                        <img src="/img/awards/award3.svg" className="max-h-[120px] w-full object-contain mr-5"></img>
                        <img src="/img/awards/award4.svg" className="max-h-[120px] w-full object-contain mr-5"></img>
                        <img src="/img/awards/award5.svg" className="max-h-[120px] w-full object-contain mr-5"></img>
                        <img src="/img/awards/award6.svg" className="max-h-[120px] w-full object-contain"></img>
                    </div>
                </div>
            </section>
        </>
    );
}