import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import HeroImageSlider from '@/src/components/HeroImageSlider';
import Link from 'next/link';
import { Modal} from 'flowbite-react';
import FacSlider from '@/src/components/FacilitiesComp/FacSlider';

export default function Facilities() {
  const [activeSlide, setActiveSlide] = useState(0);

  const handleSlideChange = (newSlide) => {
    setActiveSlide(newSlide);
  };

  const [openModal, setOpenModal] = useState();
  const props = { openModal, setOpenModal };
  
  
  return (
    <>
      <Head>
        <title>Facilities</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="relative py-0">
        <Image src="/img/big-star.svg" className="w-[20%] absolute right-[-12%] mx-auto bottom-[-23%] z-[2]" alt="Facebook" width="500" height="500"/>
        <Image src="/img/big-star.svg" className="w-[20%] absolute left-[-12%] mx-auto bottom-[-23%] z-[2]" alt="Facebook" width="500" height="500"/>
        <HeroImageSlider
            img1={"/img/facilities/hero1.png"}
            img2={"/img/facilities/hero2.png"}
        />
      </section>

      <section className="relative bg-[url('/img/white-bg.png')] bg-cover bg-no-repeat">
        <div className="container w-[85%] mx-auto">
            <div className="w-[40%]">
                <h3 className="font-GothamBook uppercase tracking-[5px] text-[#858b8c] text-[30px] md:text-[40px] 3xl:text-[50px] mb-5">Everyday Rejuvenating <span className="font-ButlerBold text-[#7ea5a2] text-[32px] md:text-[42px] 3xl:text-[52px]">Leisure</span><br></br> <span className="font-ButlerBold text-[#bda37f] text-[32px] md:text-[42px] 3xl:text-[52px]">Via</span> Evergreen Opportunities</h3>
                <p className="font-GothamBook text-[#858b8c] leading-loose mb-10 text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[18px] 3xl:text-[20px]">LEVIA’s facilities are divided across three zones with distinctive
                    environments that allow one to fully enjoy their lavish offerings.
                </p>
                <a onClick={() => props.setOpenModal('default')} className="border-solid border-2 border-[#bda37f] flex w-fit py-2 px-7 text-[#bda37f] hover:bg-[#bda37f] hover:text-white">
                    <div className="font-GothamMedium uppercase tracking-[3px] text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[20px] 3xl:text-[23px]">
                        Facilities Plan
                    </div>
                </a>
            </div>
        </div>
      </section>

      <section className="py-0 relative bg-[url('/img/white-bg.png')] bg-cover bg-no-repeat">
        <Image src="/img/big-star.svg" className="w-[20%] absolute right-[-12%] mx-auto bottom-[-0%] z-[2]" alt="Facebook" width="500" height="500"/>
        <Image src="/img/big-star.svg" className="w-[20%] absolute left-[-12%] mx-auto bottom-[-0%] z-[2]" alt="Facebook" width="500" height="500"/>
        <div className="w-full md:gap-0 flex flex-wrap justify-between items-center">
            <div className="relative w-full md:w-[48%] xl:w-[60%] fac-image">
              <Image src="/img/facilities/facilities-img.png" className="w-full rounded-tr-[58px]" alt="Facility" width={1000} height={1000}/>
            </div>
            <div className="relative w-full md:w-[48%] xl:w-[40%]">
                <div className="text-center">
                  
                    <div className="relative pb-5 w-[80%] mx-auto">
                      <Image src="/img/line-long-right.svg" className="rotate-180 w-[40%] left-[-6%] absolute top-[0%]" alt="Facebook" width="500" height="300"/>
                      <Image src="/img/line-long-right.svg" className="w-[40%] right-[-6%] absolute top-[0%]" alt="Facebook" width="500" height="300"/>
                      <h5 className="font-GothamBook uppercase tracking-[3px] text-[#bda37f] w-fit mx-auto text-[17px] md:text-[18px] lg:text-[18px] 2xl:text-[20px] 3xl:text-[25px]">Facilities</h5>
                    </div>

                    <a onClick={() => handleSlideChange(0)} className="relative text-[#858b8c] block py-5 leading-none hover:text-[#7ea5a2] hover:cursor-pointer">
                      <Image src="/img/line.svg" className="w-[30%] left-0 right-0 mx-auto absolute bottom-0" alt="Facebook" width="300" height="300"/>
                      <div className="font-Avgard capitalize tracking-[2px] w-fit mx-auto text-[17px] md:text-[18px] lg:text-[20px] 2xl:text-[20px] 3xl:text-[25px]">
                          The Aqua Zone
                      </div>
                    </a>

                    <a onClick={() => handleSlideChange(1)} className="relative text-[#858b8c] block py-5 leading-none hover:text-[#7ea5a2] hover:cursor-pointer">
                      <Image src="/img/line.svg" className="w-[30%] left-0 right-0 mx-auto absolute bottom-0" alt="Facebook" width="300" height="300"/>
                      <div className="font-Avgard capitalize tracking-[2px] w-fit mx-auto text-[17px] md:text-[18px] lg:text-[20px] 2xl:text-[20px] 3xl:text-[25px]">
                          The Eco Zone
                      </div>
                    </a>

                    <a onClick={() => handleSlideChange(2)} className="relative text-[#858b8c] block py-5 leading-none hover:text-[#7ea5a2] hover:cursor-pointer">
                      <Image src="/img/line.svg" className="w-[30%] left-0 right-0 mx-auto absolute bottom-0" alt="Facebook" width="300" height="300"/>
                      <div className="font-Avgard capitalize tracking-[2px] w-fit mx-auto text-[17px] md:text-[18px] lg:text-[20px] 2xl:text-[20px] 3xl:text-[25px]">
                          The Leisure Zone
                      </div>
                    </a>
                </div>
            </div>
        </div>
      </section>

      <section className="relative py-0">
        <FacSlider
            activeSlide={activeSlide}
            onSlideChange={handleSlideChange}
            img1={"/img/facilities/fac1.png"}
            title1={"The Aqua Zone"}
            subtitle1={"Dip your toes on a sunny day or submerge yourself in the jacuzzi as your stress floats away with the bubbling waters."}
            img2={"/img/facilities/fac2.png"}
            title2={"The Eco Zone"}
            subtitle2={"Cook up some burgers and steaks at the Grill Deck or make your way to the Open Green Lawn to bond with your loved ones as you savor warm meals and splendid views."}
            img3={"/img/facilities/fac3.png"}
            title3={"The Leisure Zone"}
            subtitle3={"Explore nature in the Forest Garden with garden swings and hammocks that envelop you in delight for a peaceful and tranquil everyday experience."}
          />
      </section>

      <Modal dismissible show={props.openModal === 'default'} size="full-screen" onClose={() => props.setOpenModal(undefined)}>
        <Modal.Header></Modal.Header>
        <Modal.Body>
          <Image src="/img/facilities/fac-plan-full.png" className="w-full" alt="Facebook" width="2000" height="2000"/>
        </Modal.Body>
      </Modal>
    </>
  )
}
