import Head from "next/head";
import Image from "next/image";
import GalleryTab from "@/src/components/GalleryComp/GalleryTab";
export default function Gallery() {
    return(
        <>
            <Head>
                <title>Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="pt-0"></section>

            <section>
                <div className="container w-[90%] sm:w-[85%] mx-auto">
                    <GalleryTab/>
                </div>
            </section>
        </>
    );
}