import Head from 'next/head';
import Image from 'next/image';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import HeroSlider from '@/src/components/Home/HeroSlider';
import Features from '@/src/components/Home/Features';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="relative pt-0">
        <Image src="/img/big-star.svg" className="w-[20%] absolute right-[-12%] mx-auto bottom-[19.5%] z-[2]" alt="Facebook" width="500" height="500"/>
        <HeroSlider />
      </section>

      <section className="relative pt-0">
      <Image src="/img/big-star.svg" className="w-[20%] absolute left-[-12%] mx-auto bottom-[19.5%] z-[2]" alt="Facebook" width="500" height="500"/>
        <div className="container w-[85%] mx-auto">
          <div className="w-full md:w-[70%] md:gap-4 flex flex-wrap justify-center m-auto">
            <Features
              img={"/img/features/usp1.png"}
              icon={"/img/features/usp2-icon.svg"}
              title={"Strategically"}
              subtitle={"Located in South KL"}
              img2={"/img/features/usp1-back.png"}
              icon2={"/img/features/usp1-back-icon.svg"}
              title2={"Low-Density"}
              subtitle2={"778 Units On 4.71-Acres Land"}
            />
            <Features
              img={"/img/features/usp2.png"}
              icon={"/img/features/usp2-icon.svg"}
              title={"Comprehensive"}
              subtitle={"Lifestyle Facilities"}
              img2={"/img/features/usp2-back.png"}
              icon2={"/img/features/usp2-back-icon.svg"}
              title2={"Green-Re"}
              subtitle2={"Green-Re"}
            />
            <Features
              img={"/img/features/usp3.png"}
              icon={"/img/features/usp3-icon.svg"}
              title={"Good Connectivity"}
              subtitle={"& Accessibility to Major Highways"}
              img2={"/img/features/usp3-back.png"}
              icon2={"/img/features/usp3-back-icon.svg"}
              title2={"Residential"}
              subtitle2={"Title"}
            />
            <Features
              img={"/img/features/usp4.png"}
              icon={"/img/features/usp4-icon.svg"}
              title={"Up to"}
              subtitle={"4 Car Parks"}
              img2={"/img/features/usp4-back.png"}
              icon2={"/img/features/usp4-back-icon.svg"}
              title2={"North & South"}
              subtitle2={"Orientation"}
            />
          </div>
        </div>
      </section>
    </>
  )
}
