import Head from 'next/head';
import Image from 'next/image';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import StickyButton from '@/src/components/StickyButton';

export default function Home() {

  useEffect( () => {
    (
      async () => {
        const LocomotiveScroll = (await import('locomotive-scroll')).default;
        const locomotiveScroll = new LocomotiveScroll();
      }
    )()

  }, [])
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="block sm:hidden"></section>
      <section className="hidden sm:flex h-screen items-center py-0">
        <Image src="/img/home/star.png" className="w-[50%] mx-auto" alt="Facebook" width="1920" height="1000"/>
      </section>

      <section className="h-fit sm:h-screen flex items-center sm:py-0">
        <div className="w-[90%] sm:w-[85%] xl:w-[50%] mx-auto relative">
          <Image src="/img/home/star.png" className="w-[30%] absolute top-[-60%] right-[10%]" alt="Facebook" width="1000" height="1000"/>
          <h1 className="font-GothamBook uppercase text-center tracking-[3px] sm:tracking-[5px] text-[#bda37f] text-[25px] sm:text-[30px] xl:text[35px] 2xl:text-[35px] 3xl:text-[50px]">An Inspired Oasis <br></br>at the City's Heart</h1>
        </div>
      </section>

      <section className="h-fit sm:h-screen flex items-center sm:py-0">
        <div className="w-[90%] sm:w-[85%] xl:w-[60%] mx-auto flex flex-col sm:flex-row items-center">
          <div>
            <div className="flex justify-center sm:justify-end mb-8 sm:mb-14">
              <Image src="/img/levia-logo.svg" className="w-[50%] ml-0" alt="Facebook" width="800" height="1000"/>
            </div>
            <p className="font-GothamBook text-center sm:text-right text-white leading-normal mb-10 lg:leading-loose text-[15px] sm:text-[17px] md:text-[18px] lg:text-[17px]">
              LEVIA comes from a combination<br></br> of the words "Leisure" and "Via", the latter meaning "by way of".</p>
            <p className="font-GothamBook text-center sm:text-right text-white leading-normal lg:leading-loose text-[15px] sm:text-[17px] md:text-[18px] lg:text-[17px]">
              This name emphasises the highly accessible nature of the development, especially with<br></br>
                surrounding lifestyle amenities and opportunities, inviting people to
                start a life journey that is easier, enjoyable and exciting.</p>
          </div>
          <div>
            <Image src="/img/home/building.png" className="w-full mx-auto" alt="Facebook" width="1920" height="1000"/>
          </div>
        </div>
      </section>
      <Image src="/img/home/aerial.png" className="w-full" alt="Facebook" width="1920" height="1200"/>
      <StickyButton></StickyButton>
    </>
  )
}
